version: '2'
services:
  default:
    links:
      - ehr:ehr
  ehr:
    image: ${EHR_DOCKER_IMAGE}
    links:
      - db:db
      - localstack:localstack
    ports:
    - 3000:3000
  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: deductions_user
      POSTGRES_DB: deductions_test
      LC_ALL: C
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3:4572
      - DEBUG=true
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=5555
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - S3_BUCKET_NAME=dev-ehr-repo-bucket
    volumes:
      - ./scripts/create-bucket.sh:/docker-entrypoint-initaws.d/create-bucket.sh
      - /var/run/docker.sock:/var/run/docker.sock
