version: "3.4"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
  ehr-repo:
    image: test-container:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=local
      - NHS_ENVIRONMENT=dev
      - S3_BUCKET_NAME=test-bucket
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=postgres
    depends_on:
      - postgres
    links:
      - postgres