version: '2'
services:
  default:
    image: nhsdev/node-dojo:d3f1f82b9b7b3af1a27395c7cf7628430c64e409
    links:
      - ehr:ehr
  ehr:
    image: ${EHR_DOCKER_IMAGE}
    links:
      - db:db
  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: deductions_user
      POSTGRES_DB: deductions_test
      LC_ALL: C
