format_version: 4
common:
  deploy_job: &deploy_job
    resources:
      - docker
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks wait_ecs

pipelines:
  "prm-deductions-ehr-repository":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
    stages:
      - build:
          clean_workspace: true
          jobs:
            dependency_check:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dep
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test
            coverage:
              artifacts:
                - build:
                    source: coverage/lcov-report
              tabs:
                coverage: lcov-report/index.html
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks coverage
            npm_install:
              resources:
                - docker
              artifacts:
                - build:
                    source: build
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build
      - docker:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: npm_install
                    source: build
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker
      - test_docker:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_docker

  "prm-deductions-ehr-repository.dev":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      app:
        pipeline: prm-deductions-ehr-repository
        stage: test_docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: check_dev
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy_job
      - smoke:
          clean_workspace: true
          jobs:
            test:
              resources:
                - deductions-private
                - dev
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks smoke

  "prm-deductions-ehr-repository.test":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      base_infra:
        pipeline: prm-deductions-infra
        stage: check_test
      dev_env:
        pipeline: prm-deductions-ehr-repository.dev
        stage: smoke
    environment_variables:
      NHS_ENVIRONMENT: test
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy_job
      - smoke:
          clean_workspace: true
          jobs:
            test:
              resources:
                - deductions-private
                - test
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks smoke
